//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntdUI.EmojiFluentFlat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntdUI.EmojiFluentFlat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAACuy9y64tS3ae9yoTpY7dUDLuF4MkUGeeOliNdQC3VmN3BEOkKAKEJehCueGGOrbphkVTakiiBNA2IMi2DEMtwzZg6134AuYjGN//R2TOOWvXOtsQIIiWahfOypgZGRm3jBgxxj/+8Wd/8s/+q//o1//m7//O7fd/97f/znd/7T/7jZ+FW7jldMvpZ7ff/PW//p/8rb96+63f+NmPcRy99XGL8ajxPeajlj5u6Zg5hHiP+UhB6VxDiLeYjjpJk38mrt7qkXMf93yMoTvpmL2PWz5q45F8NH4vx0iUWI9Agf2IKrAdg7fPIxaS84iRyoSj3ecxKCfGI05+GXFXk//2sVNvqwlffnb7K7/7e7/3Gz/7CyH08t3Pf/ZrD81M7WhV1U3hCK2Pe5xHXk0ZLu1s5DjKQyfQKSmdb0vhSLGPe4pHPOtwS2nVXLVNyZ2hdqR6xPzQxtSOyYv7EdVBaRw5PvRQmkeIDx2YxhE1BrezEY9N/Xn7xfdP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
    }
}
